// The layout spike: lay out WireViz looms with elkjs and with the dot fallback, draw both in the
// Instrument style, and write the numbers side by side.
//
//   node spike/run.ts --dir <wireviz project> [--png out] [loom ...]
//
// The project directory holds shared.yml, prepended to every loom, and the looms in src/.
// SVGs and RESULTS.md go to docs/spike/. --png also writes light and dark PNGs for a phone check.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { parseArgs } from "node:util";
import { Resvg } from "@resvg/resvg-js";
import { layoutDot } from "../src/layout/dot.ts";
import { layoutElk } from "../src/layout/elk.ts";
import type { Placement } from "../src/layout/types.ts";
import { measure, type Metrics } from "../src/metrics.ts";
import { flatten, render } from "../src/render.ts";
import { buildSheet } from "../src/sheet.ts";
import { readWireviz } from "../src/wireviz.ts";

const { values, positionals } = parseArgs({
  allowPositionals: true,
  options: { dir: { type: "string", default: "." }, png: { type: "string" } },
});
const looms = positionals.length ? positionals : ["main_electrical"];
const outDir = new URL("../docs/spike/", import.meta.url);
mkdirSync(outDir, { recursive: true });

const dir = values.dir!;
const shared = readFileSync(`${dir}/shared.yml`, "utf8");
const report: string[] = [];

for (const loom of looms) {
  const harness = readWireviz([shared, readFileSync(`${dir}/src/${loom}.yml`, "utf8")], loom);
  const sheet = buildSheet(harness);

  const t0 = performance.now();
  const elk = await layoutElk(sheet);
  const t1 = performance.now();
  const dot = layoutDot(sheet);
  const t2 = performance.now();

  const svgs: Record<string, string> = {
    elk: await render(sheet, elk, `${loom}.yml · elkjs layered, orthogonal`),
    dot: await render(sheet, dot, `${loom}.yml · dot -Tjson, splines`),
  };
  for (const [engine, svg] of Object.entries(svgs)) {
    writeFileSync(new URL(`${loom}-${engine}.svg`, outDir), svg + "\n");
    if (values.png) {
      mkdirSync(values.png, { recursive: true });
      for (const theme of ["light", "dark"] as const) {
        const png = new Resvg(flatten(svg, theme), { fitTo: { mode: "zoom", value: 2 } }).render().asPng();
        writeFileSync(`${values.png}/${loom}-${engine}-${theme}.png`, png);
      }
    }
  }

  // Same input, fresh ELK instance: the bytes must match for a strict CI diff to work.
  const again = await render(sheet, await layoutElk(sheet), `${loom}.yml · elkjs layered, orthogonal`);
  const stable = again === svgs.elk;

  report.push(section(loom, sheet.cards.length, sheet.wires.length, { elk, dot }, { elk: t1 - t0, dot: t2 - t1 }, stable, sheet));
}

writeFileSync(new URL("RESULTS.md", outDir), `# Layout spike results\n\nGenerated by \`node spike/run.ts\`. Do not edit by hand.\n${report.join("")}`);
console.log(report.join(""));

function section(loom: string, cards: number, wires: number, p: Record<string, Placement>, ms: Record<string, number>, stable: boolean, sheet: ReturnType<typeof buildSheet>): string {
  const m: Record<string, Metrics> = { elk: measure(sheet, p.elk), dot: measure(sheet, p.dot) };
  const row = (name: string, f: (x: Metrics) => string | number | null) => `| ${name} | ${f(m.elk) ?? "–"} | ${f(m.dot) ?? "–"} |`;
  return `
## ${loom}

${cards} cards, ${wires} wires. ![elk](${loom}-elk.svg) ![dot](${loom}-dot.svg)

| | elkjs | dot -Tjson |
|---|---|---|
| Canvas (px) | ${Math.round(p.elk.width)} × ${Math.round(p.elk.height)} | ${Math.round(p.dot.width)} × ${Math.round(p.dot.height)} |
${row("Total wire length (px)", (x) => x.length)}
${row("Bends", (x) => x.bends)}
${row("Crossings", (x) => x.crossings)}
${row("Wires through a card", (x) => x.throughCards)}
${row("Tags over a card or tag", (x) => x.tagOverlaps)}
| Layout time (ms) | ${Math.round(ms.elk)} | ${Math.round(ms.dot)} |

ELK output byte-identical across two runs: **${stable ? "yes" : "no"}**.
`;
}
