// Parity: read every loom in a WireViz project with ferrule and with the fork it replaces, and
// check that both found the same connectors, connections, mates and loops.
//
//   node parity/run.ts --dir <wireviz project> --python <python with the fork> [loom ...]
//
// The project directory holds shared.yml, prepended to every loom, and the looms in src/. Exits
// non-zero on any difference. This checks what is drawn, not how: the drawings need their own look.

import { execFileSync } from "node:child_process";
import { readdirSync, readFileSync } from "node:fs";
import { parseArgs } from "node:util";
import type { End, Harness } from "../src/model.ts";
import { readWireviz } from "../src/wireviz.ts";

const { values, positionals } = parseArgs({
  allowPositionals: true,
  options: { dir: { type: "string", default: "." }, python: { type: "string", default: "python3" } },
});
const dir = values.dir!;
const looms = positionals.length
  ? positionals
  : readdirSync(`${dir}/src`).filter((f) => f.endsWith(".yml")).map((f) => f.slice(0, -4)).sort();

interface Dump {
  connectors: string[];
  links: [[string, string] | null, string, number, [string, string] | null][];
  mates: [string, string][];
  loops: Record<string, [string, string][]>;
}

/** An autogenerated instance as `TEMPLATE.n`, as the dump names it. */
const name = (id: string) => id.replace(/^__(.+)_(\d+)$/, "$1.$2");
const end = (e: [string, string] | End | null) => (e == null ? "·" : Array.isArray(e) ? `${e[0]}:${e[1]}` : `${name(e.connector)}:${e.pin}`);

function fromFerrule(h: Harness): Dump {
  return {
    connectors: [...new Set(h.connectors.map((c) => name(c.id)))].sort(),
    links: h.links.map((l) => [l.from && [name(l.from.connector), l.from.pin], name(l.cable), l.wire, l.to && [name(l.to.connector), l.to.pin]]),
    mates: h.mates.map((m) => [name(m.from), name(m.to)]),
    loops: Object.fromEntries(h.connectors.filter((c) => c.loops.length).map((c) => [name(c.id), c.loops])),
  };
}

/** Each part of a dump as a sorted list of lines, so two dumps compare as multisets. */
function lines(d: Dump): Record<string, string[]> {
  return {
    connectors: d.connectors,
    links: d.links.map(([f, c, w, t]) => `${end(f)} → ${c}/${w} → ${end(t)}`).sort(),
    mates: d.mates.map(([a, b]) => `${a} == ${b}`).sort(),
    loops: Object.entries(d.loops).flatMap(([c, ls]) => ls.map(([a, b]) => `${c}: ${a}–${b}`)).sort(),
  };
}

function diff(a: string[], b: string[]): string[] {
  const count = new Map<string, number>();
  for (const x of a) count.set(x, (count.get(x) ?? 0) + 1);
  for (const x of b) count.set(x, (count.get(x) ?? 0) - 1);
  return [...count].filter(([, n]) => n).map(([x, n]) => `${n > 0 ? "fork only:  " : "ferrule only:"} ${x}`);
}

const shared = readFileSync(`${dir}/shared.yml`, "utf8");
let failed = 0;
for (const loom of looms) {
  const src = `${dir}/src/${loom}.yml`;
  const fork: Dump = JSON.parse(
    execFileSync(values.python!, [new URL("wireviz_dump.py", import.meta.url).pathname, `${dir}/shared.yml`, src], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "inherit"],
    }),
  );
  const ours = lines(fromFerrule(readWireviz([shared, readFileSync(src, "utf8")], loom)));
  const theirs = lines(fork);
  const problems = Object.keys(ours).flatMap((k) => diff(theirs[k], ours[k]).map((d) => `  ${k}: ${d}`));
  const n = ours.links.length;
  console.log(`${problems.length ? "✗" : "✓"} ${loom}: ${ours.connectors.length} connectors, ${n} connections, ${ours.mates.length} mates, ${ours.loops.length} loops`);
  for (const p of problems) console.log(p);
  if (problems.length) failed++;
}
if (failed) {
  console.log(`\n${failed} of ${looms.length} looms differ from the fork.`);
  process.exitCode = 1;
} else console.log(`\nAll ${looms.length} looms match the fork.`);
