#!/usr/bin/env python3
"""Dump what the WireViz fork reads from a loom, as JSON, for parity/run.ts to compare against.

    python3 parity/wireviz_dump.py PREPEND LOOM

Needs the fork that the project pins (for Hailey, `XDGFX/WireViz@hailey-v1`) importable. The
prepended file's text goes in front of the loom's, as the fork's --prepend does.
"""
import contextlib
import json
import re
import sys
from pathlib import Path

from wireviz.wireviz import parse
from wireviz.wv_dataclasses import AUTOGENERATED_PREFIX

FRESH = re.compile(rf"^{AUTOGENERATED_PREFIX}(.+)_\d+$")


def name(designator):
    """An autogenerated instance by its template, so the two readers' numbering can't differ."""
    m = FRESH.match(designator)
    return f"{m.group(1)}." if m else designator


def main(prepend, loom):
    text = Path(prepend).read_text() + "\n" + Path(loom).read_text()
    # The fork prints its warnings to stdout, which is where the JSON goes.
    with contextlib.redirect_stdout(sys.stderr):
        h = parse(text, return_types="harness")

    def end(pin):
        return None if pin is None else [name(pin.parent), str(pin.id)]

    links = []
    for cable in h.cables.values():
        for c in cable._connections:
            links.append([end(c.from_), name(cable.designator), int(c.via.id), end(c.to)])
    mates = [[name(m.from_), name(m.to)] for m in h.mates]
    loops = {
        name(d): [[str(a), str(b)] for a, b in c.loops] for d, c in h.connectors.items() if c.loops
    }
    json.dump(
        {"connectors": sorted({name(d) for d in h.connectors}), "links": links, "mates": mates, "loops": loops},
        sys.stdout,
    )


if __name__ == "__main__":
    main(*sys.argv[1:])
